# AWS CodeDeploy Settings
version: 0.0
os: linux
files:
    # specify files to send to destination (/ sends everything)
  - source: /
    # specify the location where deploy files will be received
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

