# AWS CodeDeploy Settings
version: 0.0
os: linux
files:
    # specify files to send to destination (/ sends everything)
  - source: /
    # specify the location where deploy files will be received
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

# grant ec2-user permissions to all files sent by CodeDeploy (to EC2)
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# Specify action during deployment
hooks:
  AfterInstall:
    # stop process that isn't connected to nginx
    - location: stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    # start program on port that isn't connected to nginx
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    # Check if new program has been started correctly
    - location: health.sh
      timeout: 60
      runas: ec2-user
