

spring:
  security:
    oauth2:
      client:
        registration:
          # google
          google:
            client-id: 391424171281-1b14ehn4ce5vhk9tcd6s013vt63m94ch.apps.googleusercontent.com
            client-secret: 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
            scope: [profile, email]

          # naver
          # registration
          naver:
            client-id: EqOxkXe0tRLUDyOYJFAu
            client-secret: SWAxqm4OY3
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: [name, email, profile_image]
            client-name: Naver

        #provider
        provider:
          naver:
            authorization_uri: 'https://nid.naver.com/oauth2.0/authorize'
            token_uri: 'https://nid.naver.com/oauth2.0/token'
            user-info-uri: 'https://openapi.naver.com/v1/nid/me'
            # returns in JSON format, so the response attribute must be received
            user_name_attribute: response
